server:
  port: 8888
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #使用小写service-id
      routes: #配置路由路径
        - id: swarm-auth
          uri: lb://swarm-auth
          predicates:
            - Path=/swarm-auth/**
          filters:
            - StripPrefix=1
        - id: swarm-ums
          uri: lb://swarm-ums
          predicates:
            - Path=/swarm-ums/**
          filters:
            - StripPrefix=1
        - id: swarm-portal
          uri: lb://swarm-portal
          predicates:
            - Path=/swarm-portal/**
          filters:
            - StripPrefix=1
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:8888/swarm-auth/rsa/publicKey' #配置RSA的公钥访问地址
  redis:
    database: 0
    port: 6379
    host: localhost
    password:
secure:
  ignore:
    urls: #配置白名单路径
      - "/doc.html"
      - "/swagger-resources/**"
      - "/swagger/**"
      - "/*/v2/api-docs"
      - "/*/*.js"
      - "/*/*.css"
      - "/*/*.png"
      - "/*/*.ico"
      - "/webjars/**"
      - "/actuator/**"
      - "/swarm-auth/oauth/token"
      - "/swarm-auth/rsa/publicKey"
      - "/swarm-portal/sso/login"
      - "/swarm-portal/sso/register"
      - "/swarm-portal/sso/getAuthCode"
      - "/swarm-portal/home/**"
      - "/swarm-ums/ums/login"
      - "/swarm-ums/ums/register"
management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
